### ISSUE TITLE
cdn - output - common

### ISSUE THREAD

**Issue by Anddd7** [Anddd7/architecture-diagram#1]

**Comment by Anddd7** [comment]
![docker-k8s-cri-oci](https://user-images.githubusercontent.com/24785373/173476060-28f8525f-a9ea-4854-84cb-c46aa959dba7.png)

**Comment by Anddd7** [comment]
![cmdb+jenkins](https://user-images.githubusercontent.com/24785373/174201692-5ff0bbf9-448a-41df-a658-594bd2c2ed04.png)

**Comment by Anddd7** [comment]
![router-proxy-gtw](https://user-images.githubusercontent.com/24785373/174201721-791bc774-9cab-4636-a713-2c26f3ef1898.png)

**Comment by Anddd7** [comment]
![8xflow-vs-ddd](https://user-images.githubusercontent.com/24785373/176106369-8f2aa731-eeb4-485b-992f-b8a9bb582533.png)

**Comment by Anddd7** [comment]
![image](https://user-images.githubusercontent.com/24785373/176583048-99b21772-d7ad-42c5-9df9-7497120e6bba.png)

**Comment by Anddd7** [comment]
![what-happends-when-k8s](https://user-images.githubusercontent.com/24785373/179442942-c64d3ac4-949a-42b9-803c-cda99d6991dd.png)

**Comment by songchengen** [comment]
先加星再看

**Comment by Anddd7** [comment]
![go-monorepo-tutorial](https://user-images.githubusercontent.com/24785373/189646243-5de20a06-ebef-45b1-87ff-9988b26b458f.png)

**Comment by Anddd7** [comment]
![architecture-methodology](https://user-images.githubusercontent.com/24785373/189646804-61d951cb-b0c9-46a2-af31-b038b3e93c3a.png)

**Comment by Anddd7** [comment]
<details>
<summary>CI/CD Value Stream Mapping</summary>
![value-stream-cicd-app](https://user-images.githubusercontent.com/24785373/201569695-42e63acc-3a8d-4a76-a6f6-b5a77332a84d.png)
![value-stream-cicd-infra](https://user-images.githubusercontent.com/24785373/201569711-6fa50703-9d3f-4e6d-8e0d-0962916c10f7.png)
</details>

**Comment by oniubi** [comment]
excellent

**Comment by Anddd7** [comment]
# devcontainers 开发环境

![devcontainers](https://user-images.githubusercontent.com/24785373/218241704-668e2384-8381-4003-8405-cbe757cd7721.png)
